name: mlai_bonoldi_ponti
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - numpy
  - matplotlib
  - jedi
  - scipy
  - scikit-learn
  - seaborn
  - pytorch
  - torchvision
  - pillow
  - threadpoolctl
variables:
  MPLBACKEND: TkAgg
